const FETCH_DATA = 'FETCH_DATA';
const UPDATE_FILTER = 'UPDATE_FILTER';
const FETCH_MAP_DATA = 'FETCH_MAP_DATA';
const UPDATE_MAP_FILTER = 'UPDATE_MAP_FILTER';

export {
  FETCH_DATA,
  UPDATE_FILTER,
  FETCH_MAP_DATA,
  UPDATE_MAP_FILTER
};
